class_name OfferRecord
## PM98 OFFER / CONTRACT record — BINARY-EXACT (docs/re/offer_record_re.md).
##
## The negotiation record the MAKE OFFER card and the FICHA's RENEW form edit is a
## struct embedded in the player at +0x6c (so rec+4 == player+0x70 = CLUB FEE and
## rec+8 == player+0x74 = YEARLY WAGE, reconciling docs/re/transfer_value_re.md §10).
## It is generated by `FUN_00576cd0(clubId, band, AV, age, posFine)` and edited by the
## ◄/► stepper handlers at 0x529a20..0x529f90. Every constant below is read from
## `extracted/Premier Manager 98/MANAGER.EXE` with tools/re/{fdump,dispscan}.py — none
## is fitted, frame-guessed or ported from the app's old invented rules.
##
## Money is stored internally in the engine's own unit (pesetas; £ = internal / 200).
## Everything here is already converted to £, which is what the app stores.

# ---- the ◄/► money stepper (UP 0x529a20 / DOWN 0x529ac0, same pair per field) ----
# The step is chosen from the CURRENT VALUE, not from how long the arrow is held —
# the app's old "accelerating hold ramp" was an invention and is gone.
#   internal 1,000,000 / 2,000,000 / 5,000,000  =  £5,000 / £10,000 / £25,000
#   thresholds  10,000,000 / 50,000,000         =  £50,000 / £250,000
const MONEY_MIN := 5_000            # DOWN bails while v <= £5,000 (test ah,0x41)
const STEP_SMALL := 5_000
const STEP_MID := 10_000
const STEP_BIG := 25_000
const STEP_T1 := 50_000             # < T1 -> STEP_SMALL
const STEP_T2 := 250_000            # < T2 -> STEP_MID, else STEP_BIG

# ---- YEARS stepper (UP 0x529e40 / DOWN 0x529f90) ---------------------------------
const YEARS_MIN := 1
const YEARS_MAX := 5

# ---- clause seeds (FUN_00576cd0 @0x576d16..0x576d71) -----------------------------
const MATCHES_TO_RENEW := 20        # rec+0x1a = 0x14, only ever on a 1-year deal
const AV_CLAUSE_BOTH := 85          # >= 0x55 -> both clause flags (rec+0x10 + rec+0x14)
const AV_CLAUSE_ONE := 80           # >= 0x50 -> one clause flag
const AV_CLAUSE_MATCH_HI := 75      # >= 0x4b -> one flag + matches target
const AV_CLAUSE_MATCH_LO := 70      # >= 0x46 -> matches target only
const POSFINE_CENTRE_FORWARD := 9   # arg5 == 9; posFine 9 = idx 8 CENTRE FORWARD
const BONUS_HI := 10_000            # rec+0xc = 2,000,000 internal (AV >= 85 striker)
const BONUS_LO := 5_000             # rec+0xc = 1,000,000 internal (AV 80..84 striker)


## The step this value takes on one arrow press.
static func step_of(v: int) -> int:
	if v < STEP_T1:
		return STEP_SMALL
	if v < STEP_T2:
		return STEP_MID
	return STEP_BIG


## ► one press. `ceiling` <= 0 means unbounded (the engine itself does not clamp up;
## the MAKE OFFER card caps at available funds, docs/re/make_offer_re.md).
static func step_up(v: int, ceiling: int = 0) -> int:
	var out := v + step_of(v)
	if ceiling > 0:
		out = mini(out, maxi(ceiling, MONEY_MIN))
	return out


## ◄ one press. At or below the £5,000 floor the engine leaves the value alone.
static func step_down(v: int) -> int:
	if v <= MONEY_MIN:
		return v
	return maxi(MONEY_MIN, v - step_of(v))


## YEARS ►. Returns the new term; the caller mirrors it onto LEFT and, when the term
## leaves 1, clears the matches-to-renew target (rec+0x1a, the binary's own rule).
static func years_up(y: int) -> int:
	return y + 1 if y < YEARS_MAX else y


static func years_down(y: int) -> int:
	return y - 1 if y > YEARS_MIN else y


## `true` while a matches-to-renew target may be carried (binary: any term > 1 zeroes
## rec+0x1a and greys the three 1-year-only clause widgets).
static func matches_clause_allowed(years: int) -> bool:
	return years <= 1


# ---- contract term at record generation (FUN_00576cd0 @0x576d09 / 0x576e5c) -------
## `r = rand(100)`; `c = 2 if r < 50 else 1`; `d = 1 if r < 25 else 0`;
## `e = 1 if r < 12 else 0`. Then, by age (age = 1997 - birthYear, FUN_00584b50):
##   age <= 22 -> c + 2      (3 or 4)
##   age <= 25 -> e + d + c  (1..4)
##   age <= 30 -> d + c      (1..3)
##   else      -> c          (1 or 2)
## LEFT is stamped equal to YEARS at generation (rec+0x19 = rec+0x18).
static func seed_years(age: int, rng: RandomNumberGenerator) -> int:
	var r := rng.randi_range(0, 99)
	var c := 2 if r < 50 else 1
	var d := 1 if r < 25 else 0
	var e := 1 if r < 12 else 0
	if age <= 22:
		return c + 2
	if age <= 25:
		return e + d + c
	if age <= 30:
		return d + c
	return c


## The clause fields the same call seeds, keyed by the row's AV (core4 >> 2) and his
## fine position. `flag_a`/`flag_b` are rec+0x10 / rec+0x14: two clause booleans whose
## mapping onto the four named checkboxes is NOT witnessed, so they are carried as
## numbered flags and never rendered under a guessed label.
static func seed_clauses(av: int, pos_fine: int, years: int) -> Dictionary:
	var out := {"flag_a": false, "flag_b": false, "matches": 0, "bonus": 0}
	var striker := pos_fine == POSFINE_CENTRE_FORWARD
	if av >= AV_CLAUSE_BOTH:
		out["flag_a"] = true
		out["flag_b"] = true
		if striker:
			out["bonus"] = BONUS_HI
	elif av >= AV_CLAUSE_ONE:
		out["flag_a"] = true
		if striker:
			out["bonus"] = BONUS_LO
	elif av >= AV_CLAUSE_MATCH_HI:
		out["flag_a"] = true
		out["matches"] = MATCHES_TO_RENEW
	elif av >= AV_CLAUSE_MATCH_LO:
		out["matches"] = MATCHES_TO_RENEW
	if not matches_clause_allowed(years):
		out["matches"] = 0
	return out


# ---- the on-screen AV (FUN_00534570, transfer_value_re.md §1) ---------------------
## The TRANSFER MARKET / offer-card "AV" cell is core4 >> 2, NOT the CA attribute and
## NOT the 6-attr RATING (that one is Morale.av6 / FUN_00581e60).
static func av_of(p: Dictionary) -> int:
	var a: Variant = p.get("attrs", {})
	if not (a is Dictionary) or (a as Dictionary).is_empty():
		return 0
	var d: Dictionary = a
	return (int(d.get("VE", 0)) + int(d.get("RE", 0)) + int(d.get("AG", 0))
		+ int(d.get("CA", 0))) >> 2
