class_name OfferRecord
## PM98 OFFER / CONTRACT record — BINARY-EXACT (docs/re/offer_record_re.md).
##
## The negotiation record the MAKE OFFER card and the FICHA's RENEW form edit is a
## struct embedded in the player at +0x6c (so rec+4 == player+0x70 = CLUB FEE and
## rec+8 == player+0x74 = YEARLY WAGE, reconciling docs/re/transfer_value_re.md §10).
## It is generated by `FUN_00576cd0(clubId, band, AV, age, posFine)` and edited by the
## ◄/► stepper handlers at 0x529a20..0x529f90. Every constant below is read from
## `extracted/Premier Manager 98/MANAGER.EXE` with tools/re/{fdump,dispscan}.py — none
## is fitted, frame-guessed or ported from the app's old invented rules.
##
## Money is stored internally in the engine's own unit (pesetas; £ = internal / 200).
## Everything here is already converted to £, which is what the app stores.

# ---- the ◄/► money stepper (UP 0x529a20 / DOWN 0x529ac0, same pair per field) ----
# The step is chosen from the CURRENT VALUE, not from how long the arrow is held —
# the app's old "accelerating hold ramp" was an invention and is gone.
#   internal 1,000,000 / 2,000,000 / 5,000,000  =  £5,000 / £10,000 / £25,000
#   thresholds  10,000,000 / 50,000,000         =  £50,000 / £250,000
const MONEY_MIN := 5_000            # DOWN bails while v <= £5,000 (test ah,0x41)
const STEP_SMALL := 5_000
const STEP_MID := 10_000
const STEP_BIG := 25_000
const STEP_T1 := 50_000             # < T1 -> STEP_SMALL
const STEP_T2 := 250_000            # < T2 -> STEP_MID, else STEP_BIG

# ---- YEARS stepper (UP 0x529e40 / DOWN 0x529f90) ---------------------------------
const YEARS_MIN := 1
const YEARS_MAX := 5

# ---- clause seeds (FUN_00576cd0 @0x576d16..0x576d71) -----------------------------
const MATCHES_TO_RENEW := 20        # rec+0x1a = 0x14, only ever on a 1-year deal
const AV_CLAUSE_BOTH := 85          # >= 0x55 -> both clause flags (rec+0x10 + rec+0x14)
const AV_CLAUSE_ONE := 80           # >= 0x50 -> one clause flag
const AV_CLAUSE_MATCH_HI := 75      # >= 0x4b -> one flag + matches target
const AV_CLAUSE_MATCH_LO := 70      # >= 0x46 -> matches target only
const POSFINE_CENTRE_FORWARD := 9   # arg5 == 9; posFine 9 = idx 8 CENTRE FORWARD
const BONUS_HI := 10_000            # rec+0xc = 2,000,000 internal (AV >= 85 striker)
const BONUS_LO := 5_000             # rec+0xc = 1,000,000 internal (AV 80..84 striker)


## The step this value takes on one arrow press.
static func step_of(v: int) -> int:
	if v < STEP_T1:
		return STEP_SMALL
	if v < STEP_T2:
		return STEP_MID
	return STEP_BIG


## ► one press. `ceiling` <= 0 means unbounded (the engine itself does not clamp up;
## the MAKE OFFER card caps at available funds, docs/re/make_offer_re.md).
static func step_up(v: int, ceiling: int = 0) -> int:
	var out := v + step_of(v)
	if ceiling > 0:
		out = mini(out, maxi(ceiling, MONEY_MIN))
	return out


## ◄ one press. At or below the £5,000 floor the engine leaves the value alone.
static func step_down(v: int) -> int:
	if v <= MONEY_MIN:
		return v
	return maxi(MONEY_MIN, v - step_of(v))


## YEARS ►. Returns the new term; the caller mirrors it onto LEFT and, when the term
## leaves 1, clears the matches-to-renew target (rec+0x1a, the binary's own rule).
static func years_up(y: int) -> int:
	return y + 1 if y < YEARS_MAX else y


static func years_down(y: int) -> int:
	return y - 1 if y > YEARS_MIN else y


## `true` while a matches-to-renew target may be carried (binary: any term > 1 zeroes
## rec+0x1a and greys the three 1-year-only clause widgets).
static func matches_clause_allowed(years: int) -> bool:
	return years <= 1


# ---- contract term at record generation (FUN_00576cd0 @0x576d09 / 0x576e5c) -------
## `r = rand(100)`; `c = 2 if r < 50 else 1`; `d = 1 if r < 25 else 0`;
## `e = 1 if r < 12 else 0`. Then, by age (age = 1997 - birthYear, FUN_00584b50):
##   age <= 22 -> c + 2      (3 or 4)
##   age <= 25 -> e + d + c  (1..4)
##   age <= 30 -> d + c      (1..3)
##   else      -> c          (1 or 2)
## LEFT is stamped equal to YEARS at generation (rec+0x19 = rec+0x18).
static func seed_years(age: int, rng: RandomNumberGenerator) -> int:
	var r := rng.randi_range(0, 99)
	var c := 2 if r < 50 else 1
	var d := 1 if r < 25 else 0
	var e := 1 if r < 12 else 0
	if age <= 22:
		return c + 2
	if age <= 25:
		return e + d + c
	if age <= 30:
		return d + c
	return c


# ---- clause -> CONTRACT-panel checkbox map (WITNESSED 2026-07-24) ----------------
# The four PLAYER INFORMATION checkboxes, in the row order the card draws them
# (PlayerInfoScreen.CB_YS). The record field behind each was read straight off five live
# cards whose AV band and term were known -- Southgate 81 (one box), Keane 89 MID (two),
# Sheringham 75 1y (renders the literal "(20)"), Cole 83 CF (renders "£5,000") and
# Nevland 3y (none): screenshots/wine-captures-2026-07-24-clause-labels/,
# docs/re/offer_record_re.md §5.1. Before that capture these were carried as unnamed
# numbered flags; they are no longer a guess.
const CLAUSE_FREE_IF_RELEGATED := 0    # rec+0x10
const CLAUSE_MATCHES_TO_RENEW := 1     # rec+0x1a
const CLAUSE_SCORING_BONUS := 2        # rec+0x0c
const CLAUSE_HOUSE_AND_CAR := 3        # rec+0x14
const CLAUSE_LABELS := ["Free if relegated", "Matches to renew", "Scoring bonus",
	"House and car"]


## The clause fields the same call seeds, keyed by the row's AV (core4 >> 2) and his fine
## position. Returns the record fields under their witnessed names plus `indices`, the
## sorted checkbox rows the CONTRACT panel ticks (`player["clauses"]`).
static func seed_clauses(av: int, pos_fine: int, years: int) -> Dictionary:
	var out := {"free_if_relegated": false, "house_and_car": false, "matches": 0,
		"bonus": 0, "indices": []}
	var striker := pos_fine == POSFINE_CENTRE_FORWARD
	if av >= AV_CLAUSE_BOTH:
		out["free_if_relegated"] = true
		out["house_and_car"] = true
		if striker:
			out["bonus"] = BONUS_HI
	elif av >= AV_CLAUSE_ONE:
		out["free_if_relegated"] = true
		if striker:
			out["bonus"] = BONUS_LO
	elif av >= AV_CLAUSE_MATCH_HI:
		out["free_if_relegated"] = true
		out["matches"] = MATCHES_TO_RENEW
	elif av >= AV_CLAUSE_MATCH_LO:
		out["matches"] = MATCHES_TO_RENEW
	if not matches_clause_allowed(years):
		out["matches"] = 0
	var idx: Array = []
	if out["free_if_relegated"]:
		idx.append(CLAUSE_FREE_IF_RELEGATED)
	if int(out["matches"]) > 0:
		idx.append(CLAUSE_MATCHES_TO_RENEW)
	if int(out["bonus"]) > 0:
		idx.append(CLAUSE_SCORING_BONUS)
	if out["house_and_car"]:
		idx.append(CLAUSE_HOUSE_AND_CAR)
	out["indices"] = idx
	return out


# ---- the asking price + the accept test (FUN_005889c0 / 0x584960 / 0x5849a0) -----
# `player+0x9a` is a PER-MILLE price modifier: init 1000 (= full book value), clamped
# to [500, 1250] by the adder at 0x584960, and re-set each week for CENTRE FORWARDS by
# FUN_005849a0 from a goals-per-minute ratio. `player+0x98` is the TRANSFER-LIST flag
# (setter FUN_00588620 pushes the player into the global list at 0x66c160 — the very
# list the TRANSFER screen's draw routine FUN_00532a50 enumerates), and it knocks a
# further 200‰ off. The accept test compares the bid against the modified ask.
const PRICE_MOD_FULL := 1000        # _DAT_00638fb8, the init value at 0x581d2f
const PRICE_MOD_MIN := 500          # clamp lo (0x584960)
const PRICE_MOD_MAX := 1250         # clamp hi (0x584960)
const PRICE_MOD_LISTED := 200       # _DAT_00638fb0, subtracted when player+0x98 is set

# FUN_005849a0's ladder, in the order the binary tests it. `thr` is the striker's
# goals-per-minute threshold, x10000: 60 when arg2 < 4, 47 when arg2 < 7, else 36.
const PRICE_MOD_THRESHOLDS := [[4, 60], [7, 47]]
const PRICE_MOD_THRESHOLD_LOW := 36
const PRICE_MOD_LADDER := [[0, 1000], [13, 900], [24, 800], [39, 700], [50, 600]]
const PRICE_MOD_FLOOR := 500


## The per-mille modifier a player carries. Defaults to the binary's own init value.
static func price_modifier(p: Dictionary) -> int:
	return clampi(int(p.get("price_modifier", PRICE_MOD_FULL)), PRICE_MOD_MIN, PRICE_MOD_MAX)


## FUN_00584960: nudge the modifier by `delta`, clamped to [500, 1250].
static func price_modifier_add(m: int, delta: int) -> int:
	return clampi(m + delta, PRICE_MOD_MIN, PRICE_MOD_MAX)


## FUN_005849a0's striker ladder. `ratio` is `goals * 10000 / minutes` over career +
## season, `arg2` the club field the caller passes from club+0x58. Returns the per-mille
## modifier. NOT DRIVEN YET: the app accumulates no per-player minutes or goals
## (docs/re/statistics_screen_re.md's declared gap), so nothing calls this in anger —
## it is ported so the moment a season-stat store lands the modifier plugs straight in.
static func price_modifier_of(ratio: int, arg2: int) -> int:
	var thr := PRICE_MOD_THRESHOLD_LOW
	for row in PRICE_MOD_THRESHOLDS:
		if arg2 < int(row[0]):
			thr = int(row[1])
			break
	for row in PRICE_MOD_LADDER:
		if ratio >= thr - int(row[0]):
			return int(row[1])
	return PRICE_MOD_FLOOR


## The asking fee for a player whose book value is `fee` (FUN_005889c0): the modifier
## only ever DISCOUNTS — at or above 1000‰ the engine asks full book value.
static func asking_fee(fee: int, modifier: int, listed: bool) -> int:
	var m := modifier - (PRICE_MOD_LISTED if listed else 0)
	if m >= PRICE_MOD_FULL:
		return fee
	return int(float(fee) * float(m) * 0.001)


## The accept test itself: a bid is taken iff it reaches the modified ask.
static func offer_accepted(bid: int, fee: int, modifier: int, listed: bool) -> bool:
	return bid >= asking_fee(fee, modifier, listed)


# ---- the on-screen AV (FUN_00534570, transfer_value_re.md §1) ---------------------
## The TRANSFER MARKET / offer-card "AV" cell is core4 >> 2, NOT the CA attribute and
## NOT the 6-attr RATING (that one is Morale.av6 / FUN_00581e60).
static func av_of(p: Dictionary) -> int:
	var a: Variant = p.get("attrs", {})
	if not (a is Dictionary) or (a as Dictionary).is_empty():
		return 0
	var d: Dictionary = a
	return (int(d.get("VE", 0)) + int(d.get("RE", 0)) + int(d.get("AG", 0))
		+ int(d.get("CA", 0))) >> 2
