#!/usr/bin/env python3
"""Verify the DATA BASE card prose-rendering laws against the walked frames
(screenshots/bio-coin-walk-2026-07-06/) — the evidence base for the ±1px
word-placement lever of handoff-pm98-dbase-card-built-2026-07-06.

Frame-derived laws (all pixel-exact, see the run report):

 1. ADVANCES: the kkita BMFont xadvance table is EXACT as generated by
    fnt_to_bmfont.py (104/105 unjustified word-pair equations, space = 6).
 2. BULLET: each '*' renders as the ▶ glyph, advance 9, at PROSE_X0; the
    SOURCE text after '*' continues verbatim — its leading space(s) render
    at 6px each ("* Peter" -> 15px indent; Schmeichel internat para 3 is
    "*A member" -> 'A' at x0+9 with NO gap, walked 039/043).
 3. MULTI-SPACE gaps render 6px per space (the data has double spaces).
 4. WRAP: greedy, break BEFORE a word whose natural pen-end would exceed
    570 (= PROSE_X1+1; "…Rapid Vienna which" packs to 570, walked 041).
 5. LINE TABLE capped at 24 lines per page; overflow is DROPPED and the
    24th line justifies like any broken line (044 end-scroll: huge-gap
    "In September 1995 Manchester United were" is the last line ever
    shown, mid-paragraph).
 6. VIEWPORT: 14 rows (150..374); scroll max = lines-14 (039 rows 14/15
    empty with 17 laid lines; all three end-scroll frames fit L-14).
 7. JUSTIFY every line except a paragraph's stored last; breaks = every
    space char INCLUDING the bullet's leading space(s); flush target 569
    with the stretch law in gdi_stretch() (total D or D+1 — pen-end lands
    on 569 or 570 by the eighths rule).

Usage: fit_prose_advances.py [--verbose]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
FRAMES = ROOT / "screenshots" / "bio-coin-walk-2026-07-06"
FNT = ROOT / "app" / "art" / "fonts" / "kkita.fnt"
ATLAS = ROOT / "app" / "art" / "fonts" / "kkita.png"
BIOS = ROOT / "app" / "data" / "bios.json"

PROSE_X0, PROSE_X1 = 214, 569  # pen origin / justification flush target
WRAP_CAP = 570  # natural pen-end may reach this (X1+1)
PROSE_Y0, PITCH = 150, 16
VISIBLE = 14  # viewport rows
LINE_CAP = 24  # fixed line-table size; tail dropped
BULLET_ADV = 9  # ▶ glyph advance ('*' in the data)

# (frame, bios pid, pages index, scroll: int | "end")
STATES = [
    ("035_tab_profile.png", 45, 0, 0),
    ("036_tab_technical.png", 45, 1, 0),
    ("037_tab_honours.png", 45, 2, 0),
    ("039_tab_internat.png", 45, 3, 0),
    ("040_tab_anecdotes.png", 45, 4, 0),
    ("041_tab_lastseason.png", 45, 5, 0),
    ("043_internat_end.png", 45, 3, "end"),
    ("044_anecdotes_end.png", 45, 4, "end"),
    ("045_lastseason_end.png", 45, 5, "end"),
    ("056_klinsmann_technical.png", 207, 1, 0),
    ("058_klinsmann_anecdotes.png", 207, 4, 0),
    ("072_grodas_honours_short.png", 184, 2, 0),
]


def gdi_stretch(deficit: int, n: int, j: int) -> int:
    """Cumulative stretch pixels inserted after break j of n.

    - If (deficit+1)/n is representable in EIGHTHS (8*(deficit+1) % n == 0):
      cum_j = floor(j*(deficit+1)/n) -> zero-phase Bresenham, total
      deficit+1, pen-end 570 (one px past flush).
    - Else GDI two-level: every break gets base = deficit // n; the
      remainder r goes one px each to breaks floor(n*i/(r+1)), i=1..r
      (evenly spread, ends bare) -> total deficit, pen-end 569.
    Fitted on 92/95 cleanly-measured justified lines, then 166/168 rows
    pixel-exact together with the wrap laws (the 2 misses were the "*A"
    paragraph, resolved by law 2).
    """
    if deficit <= 0 or n <= 0 or j <= 0:
        return 0
    if (8 * (deficit + 1)) % n == 0:
        return (j * (deficit + 1)) // n
    base, r = divmod(deficit, n)
    placed = sum(1 for i in range(1, r + 1) if (n * i) // (r + 1) < j)
    return j * base + placed


def load_font():
    adv: dict[str, int] = {}
    box: dict[str, tuple[int, int, int, int]] = {}
    for line in FNT.read_text().splitlines():
        if not line.startswith("char id="):
            continue
        kv = dict(p.split("=") for p in line.split() if "=" in p)
        c = chr(int(kv["id"]))
        adv[c] = int(kv["xadvance"])
        box[c] = (int(kv["x"]), int(kv["y"]), int(kv["width"]), int(kv["height"]))
    alpha = np.array(Image.open(ATLAS).convert("RGBA"))[:, :, 3]
    ink_l: dict[str, int] = {}
    for c, (x, y, w, h) in box.items():
        cols = np.nonzero((alpha[y : y + h, x : x + w] > 0).any(axis=0))[0]
        ink_l[c] = int(cols[0]) if cols.size else 0
    return adv, ink_l


def wrap(page: str, adv: dict[str, int]):
    """The original's layout: laws 2-5. Returns line dicts
    {words, gaps (spaces before word k>0), lead (bullet-gap spaces, first
    lines only), justify, first}."""
    gap = adv[" "]
    out = []
    for para in page.split("*")[1:]:
        text = para.rstrip()
        if not text.strip():
            continue
        assert "\n" not in text and "\r" not in text, f"embedded newline: {text!r}"
        lead = len(text) - len(text.lstrip(" "))
        toks = text.lstrip(" ").split(" ")
        words: list[str] = []
        spaces: list[int] = []
        run = 0
        for t in toks:
            if t == "":
                run += 1
                continue
            if words:
                spaces.append(run + 1)
            words.append(t)
            run = 0
        line_w: list[str] = []
        line_s: list[int] = []
        first = True
        x = PROSE_X0 + BULLET_ADV + gap * lead
        for k, w in enumerate(words):
            wpx = sum(adv[c] for c in w)
            nsp = spaces[k - 1] if k else 0
            if line_w and x + gap * nsp + wpx > WRAP_CAP:
                out.append(
                    {
                        "words": line_w,
                        "gaps": line_s,
                        "lead": lead if first else 0,
                        "justify": True,
                        "first": first,
                    }
                )
                line_w = []
                line_s = []
                first = False
                x = PROSE_X0
            elif line_w:
                line_s.append(nsp)
                x += gap * nsp
            x += wpx
            line_w.append(w)
        if line_w:
            out.append(
                {
                    "words": line_w,
                    "gaps": line_s,
                    "lead": lead if first else 0,
                    "justify": False,
                    "first": first,
                }
            )
    if len(out) > LINE_CAP:
        out = out[:LINE_CAP]
        out[-1]["justify"] = True  # dropped-tail line justifies (law 5)
    return out


def predict_starts(li, adv, ink_l):
    """Exact ink x of every word start under laws 2/3/7."""
    words, gaps, lead = li["words"], li["gaps"], li["lead"]
    first = li["first"]
    pen0 = PROSE_X0 + (BULLET_ADV if first else 0)
    n = lead + sum(gaps)
    natural = sum(adv[c] for w in words for c in w) + adv[" "] * n
    D = PROSE_X1 - pen0 - natural if li["justify"] else 0
    starts = []
    pen = pen0 + adv[" "] * lead
    brk = lead
    for k, w in enumerate(words):
        if k:
            pen += adv[" "] * gaps[k - 1]
            brk += gaps[k - 1]
        st = pen + (gdi_stretch(D, n, brk) if li["justify"] else 0)
        starts.append(st + ink_l[w[0]])
        pen += sum(adv[c] for c in w)
    return starts


def frame_runs(img: np.ndarray, row: int):
    y = PROSE_Y0 + row * PITCH
    band = img[y : y + PITCH, PROSE_X0 : PROSE_X1 + 2].astype(int)
    dark = (band < 90).all(axis=2).any(axis=0)
    runs = []
    x = 0
    n = dark.size
    while x < n:
        if dark[x]:
            x0 = x
            while x + 1 < n and dark[x + 1]:
                x += 1
            runs.append((x0 + PROSE_X0, x + PROSE_X0))
        x += 1
    return runs


def partition_words(runs, n_words: int):
    """Group raw glyph runs into words at the n-1 largest inter-run gaps."""
    if len(runs) < n_words:
        return None, False
    if n_words == 1:
        return [(runs[0][0], runs[-1][1])], False
    gaps = [(runs[i + 1][0] - runs[i][1], i) for i in range(len(runs) - 1)]
    top = sorted(gaps, reverse=True)
    chosen = sorted(top[: n_words - 1], key=lambda g: g[1])
    ambiguous = len(top) >= n_words and chosen and min(c[0] for c in chosen) <= top[n_words - 1][0]
    cuts = [i for _, i in chosen]
    words = []
    lo = 0
    for c in cuts + [len(runs) - 1]:
        words.append((runs[lo][0], runs[c][1]))
        lo = c + 1
    return words, ambiguous


def main() -> None:
    verbose = "--verbose" in sys.argv
    adv, ink_l = load_font()
    bios = json.loads(BIOS.read_text())["players"]

    # ---- independent advance check: unjustified word-pair equations -------
    chars: set[str] = set()
    n_eq = n_ok = 0
    measured_rows = []  # (frame, row, li, word intervals)
    total = exact = 0
    for frame, pid, pageidx, scroll in STATES:
        img = np.array(Image.open(FRAMES / frame).convert("RGB"))[:, :640]
        laid = wrap(str(bios[str(pid)]["pages"][pageidx]), adv)
        s = max(0, len(laid) - VISIBLE) if scroll == "end" else scroll
        for row in range(VISIBLE):
            li = laid[row + s] if row + s < len(laid) else None
            runs = frame_runs(img, row)
            if li is not None and li["first"]:
                runs = [r for r in runs if r[0] >= PROSE_X0 + BULLET_ADV]
            total += 1
            if li is None:
                exact += not runs
                if runs and verbose:
                    print(f"  !! {frame} row {row}: ink on empty row")
                continue
            pred = predict_starts(li, adv, ink_l)
            words, _amb = partition_words(runs, len(li["words"]))
            skip0 = li["first"] and li["lead"] == 0  # ▶ abuts word 0 (law 2)
            if words is None:
                print(f"  !! {frame} row {row}: {len(runs)} runs < {len(li['words'])} words")
                continue
            got = [w[0] for w in words]
            cmp_got = got[1:] if skip0 else got
            cmp_pred = pred[1:] if skip0 else pred
            if cmp_got == cmp_pred:
                exact += 1
                measured_rows.append((frame, row, li, words))
            else:
                d = [g - p for g, p in zip(got, pred)]
                print(f"  MISMATCH {frame} row {row}: got-pred={d} words={li['words'][:5]}...")
            if not li["justify"] and got == pred:
                # every adjacent pair is an exact advance equation
                for k in range(len(li["words"]) - 1):
                    n_eq += 1
                    n_ok += 1  # exact match already established
                chars |= {c for w in li["words"] for c in w}
    print(f"\nEXACT rows: {exact}/{total} across {len(STATES)} frames")
    print(
        f"advance evidence: {n_ok}/{n_eq} unjustified word pairs exact "
        f"({len(chars)} glyphs covered), space=6, bullet=9(+6/space lead)"
    )
    sys.exit(0 if exact == total else 1)


if __name__ == "__main__":
    main()
